In [2]:
import pandas as pd
df = pd.DataFrame({
    'name':['A','B','C'],
    'score':[90,80,85]
})
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'score'], dtype='str')

In [3]:
df_chain = pd.DataFrame([[0,0],[1,0],[-1,0]],columns=list('AB'))
print(df_chain)
df_chain.loc[df_chain.A!=0,'B'] = 1
df_chain

   A  B
0  0  0
1  1  0
2 -1  0

   A  B
0  0  0
1  1  1
2 -1  1

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/learn_pandas.csv',usecols=['School','Grade','Name','Gender','Weight','Transfer'])
df_demo=df.set_index('Name')
print(df_demo.head())
print(df_demo.iloc[1,1])
print(df_demo.iloc[[0,1],[0,1]])
print(df_demo.iloc[1:4,2:4])
print(df_demo.iloc[lambda x:slice(1,4)])
print(df_demo.iloc[(df_demo.Weight>80).values].head())

               School      Grade  Gender  Weight Transfer
Name
Gaopeng Yang        A   Freshman  Female    46.0        N
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N
Gaojuan You         C  Sophomore    Male    74.0        N
Freshman
               School     Grade
Name
Gaopeng Yang        A  Freshman
Changqiang You      B  Freshman
                Gender  Weight
Name
Changqiang You    Male    70.0
Mei Sun           Male    89.0
Xiaojuan Sun    Female    41.0
               School      Grade  Gender  Weight Transfer
Name
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N
               School      Grade Gender  Weight Transfer
Name
Mei Sun             A     Senior   Male    89.0        N
Qiang Zheng         A     Senior   Male    87.0        N
Qiang Han           B   Freshman   Male    87.0        N
Chengpeng Zhou      C     Senior   Male    81.0        N
Feng Han            A  Sophomore   Male    82.0        N

In [5]:
print(df_demo.head())
print(df_demo.School.iloc[1])
print(df_demo.School.iloc[1:5:2])
print(df.query('((School == "A")&'
         ' (Grade == "Senior")&'
         ' (Weight > 70))|'
         '((School == "B")&'
         ' (Grade != "Senior")&'
         ' (Weight > 80))'))
df.query('Weight > Weight.mean()').head()

               School      Grade  Gender  Weight Transfer
Name
Gaopeng Yang        A   Freshman  Female    46.0        N
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N
Gaojuan You         C  Sophomore    Male    74.0        N
B
Name
Changqiang You    B
Xiaojuan Sun      C
Name: School, dtype: str
    School     Grade            Name Gender  Weight Transfer
2        A    Senior         Mei Sun   Male    89.0        N
23       A    Senior     Qiang Zheng   Male    87.0        N
38       B  Freshman       Qiang Han   Male    87.0        N
99       B  Freshman  Changpeng Zhao   Male    83.0        N
134      A    Senior      Gaoli Zhao   Male    83.0        N
171      A    Senior  Xiaofeng Zhang   Male    80.0        N
198      A    Senior   Chengmei Shen   Male    71.0        N

   School      Grade            Name  Gender  Weight Transfer
1       B   Freshman  Changqiang You    Male    70.0        N
2       A     Senior         Mei Sun    Male    89.0        N
4       C  Sophomore     Gaojuan You    Male    74.0        N
10      A   Freshman   Xiaopeng Zhou    Male    74.0        N
14      D     Senior    Xiaomei Zhou  Female    57.0        N

In [6]:
print(df.query('(Grade not in ["Freshman","Sophomore"]) and'
         '(Gender == "Male")').head())
print(df.query('Grade == ["Junior","Senior"]').head())
low,high = 70,80
print(df.query('Weight.between(@low,@high)').head())

   School   Grade           Name Gender  Weight Transfer
2       A  Senior        Mei Sun   Male    89.0        N
16      D  Junior  Xiaoqiang Qin   Male    68.0        N
17      D  Junior      Peng Wang   Male    65.0        N
18      D  Senior   Xiaofeng Sun   Male    71.0        N
21      A  Senior  Xiaopeng Shen   Male    62.0      NaN
   School   Grade           Name  Gender  Weight Transfer
2       A  Senior        Mei Sun    Male    89.0        N
7       D  Junior  Gaoqiang Qian  Female    50.0        N
9       B  Junior        Juan Xu  Female     NaN        N
11      D  Junior    Xiaoquan Lv  Female    43.0        N
12      A  Senior       Peng You  Female    48.0      NaN
   School      Grade            Name Gender  Weight Transfer
1       B   Freshman  Changqiang You   Male    70.0        N
4       C  Sophomore     Gaojuan You   Male    74.0        N
10      A   Freshman   Xiaopeng Zhou   Male    74.0        N
18      D     Senior    Xiaofeng Sun   Male    71.0        N
35      B   Freshman      Gaoli Zhao   Male    78.0        N

In [7]:
df_sample = pd.DataFrame({'id':list('abcde'),
                          'value':[1,2,3,4,90]})
print(df_sample)
df_sample.sample(3,replace=True,weights=df_sample.value)

  id  value
0  a      1
1  b      2
2  c      3
3  d      4
4  e     90

  id  value
4  e     90
3  d      4
4  e     90

In [14]:
df_multi = df.set_index(['School','Grade'])
print(df_multi.head())
df_multi = df_multi.sort_index()
print(df_multi.loc[('A','Junior')].head())
print(df_multi.loc[[('A','Senior'),('B','Freshman')]].head())
print(df_multi.loc[df_multi.Weight > 70].head())
df_multi.loc[lambda x:('A','Junior')].head()

                            Name  Gender  Weight Transfer
School Grade
A      Freshman     Gaopeng Yang  Female    46.0        N
B      Freshman   Changqiang You    Male    70.0        N
A      Senior            Mei Sun    Male    89.0        N
C      Sophomore    Xiaojuan Sun  Female    41.0        N
       Sophomore     Gaojuan You    Male    74.0        N
                      Name  Gender  Weight Transfer
School Grade
A      Junior   Feng Zheng  Female    51.0        N
       Junior    Mei Zhang  Female    44.0        N
       Junior  Xiaoli Wang    Male    70.0        N
       Junior     Qiang Lv  Female    42.0        N
       Junior      Mei Sun  Female    50.0        N
                         Name  Gender  Weight Transfer
School Grade
A      Senior         Mei Sun    Male    89.0        N
       Senior        Peng You  Female    48.0      NaN
       Senior       Qiang Chu  Female    50.0        N
       Senior   Xiaopeng Shen    Male    62.0      NaN
       Senior  Changqiang Sun  Female    55.0        N
                          Name Gender  Weight Transfer
School Grade
A      Freshman  Xiaopeng Zhou   Male    74.0        N
       Freshman    Chunli Zhao   Male    83.0        N
       Freshman    Changmei Lv   Male    75.0        N
       Freshman     Qiang Feng   Male    80.0        N
       Senior          Mei Sun   Male    89.0        N

                      Name  Gender  Weight Transfer
School Grade
A      Junior   Feng Zheng  Female    51.0        N
       Junior    Mei Zhang  Female    44.0        N
       Junior  Xiaoli Wang    Male    70.0        N
       Junior     Qiang Lv  Female    42.0        N
       Junior      Mei Sun  Female    50.0        N