In [128]:
import pandas as pd
df = pd.DataFrame({
    "大区": ["东","东","南","南","东","南"],
    "品类": ["数码","服饰","数码","服饰","数码","数码"],
    "月份": pd.to_datetime(["2024-01","2024-01","2024-01","2024-02","2024-02","2024-02"]),
    "销售额": [100,80,120,90,150,130],
    "订单数": [5,4,6,3,7,6],
})
pt = df.pivot_table(
    index=["大区"],columns="月份",values="销售额",
    aggfunc=["sum","mean"],fill_value=0,margins=True,margins_name="合计"
)
print(pt)
pt2 = df.pivot_table(index="大区",columns="月份",values=["销售额","订单数"],
aggfunc="sum",fill_value=0)
print(pt2.swaplevel(axis=1).sort_index(axis=1))

                   sum                                         mean  \
月份 2024-01-01 00:00:00 2024-02-01 00:00:00   合计 2024-01-01 00:00:00
大区
东                  180                 150  330                90.0
南                  120                 220  340               120.0
合计                 300                 370  670               100.0


月份 2024-02-01 00:00:00          合计
大区
东           150.000000  110.000000
南           110.000000  113.333333
合计          123.333333  111.666667
月份 2024-01-01      2024-02-01
          订单数  销售额        订单数  销售额
大区
东           9  180          7  150
南           6  120          9  220

In [129]:
L = []
def my_func(x):
    return 2 * x
for i in range(5):
    L.append(my_func(i))
print(L)
print([my_func(i) for i in range(5)])
print([m+'_'+n for m in ['a','b'] for n in ['c','d']])

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
['a_c', 'a_d', 'b_c', 'b_d']

In [130]:
L = [1,2,3,4,5,6,7]
print([i if i <= 5 else 5 for i in L])
my_func = lambda x:2*x
print(my_func(3))
multi_para_func = lambda a,b:a+b
print(multi_para_func(1,2))
print([(lambda x:2*x)(i)for i in range(5)])
print(list(map(lambda x:2*x,range(5))))
print(list(map(lambda x,y:str(x)+'_'+y,range(5),list('abcde'))))

[1, 2, 3, 4, 5, 5, 5]
6
3
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
['0_a', '1_b', '2_c', '3_d', '4_e']

In [131]:
L1,L2,L3 = list('abc'),list('def'),list('hij')
print(list(zip(L1,L2,L3)))
print(tuple(zip(L1,L2,L3)))
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)
L = list('abcd')
for index,value in enumerate(L):
    print(index,value)
for index,value in zip(range(len(L)),L):
    print(index,value)
print(dict(zip(L1,L2)))
zipped = list(zip(L1,L2,L3))
print(zipped)
print(list(zip(*zipped)))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]
(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))
a d h
b e i
c f j
0 a
1 b
2 c
3 d
0 a
1 b
2 c
3 d
{'a': 'd', 'b': 'e', 'c': 'f'}
[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]
[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

In [132]:
import numpy as np
print(np.array([1,2,3]))
print(np.linspace(1,5,11))
print(np.arange(1,5,2))
print(np.zeros((2,3)))
print(np.eye(3))
print(np.eye(3,k=1))
print(np.full((2,3),10))
print(np.full((2,3),[1,2,3]))

[1 2 3]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
[1 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[10 10 10]
 [10 10 10]]
[[1 2 3]
 [1 2 3]]

In [133]:
import numpy as np
print(np.random.rand(3))
print(np.random.rand(3,3))
a,b = 5,15
print((b-a)*np.random.rand(3)+a)
print(np.random.randn(3))
print(np.random.randn(2,2))
sigma,mu = 2.5,3
print(mu+np.random.randn(3)*sigma)
low,high,size = 5,15,(2,2)
print(np.random.randint(low,high,size))

[0.71518937 0.60276338 0.54488318]
[[0.4236548  0.64589411 0.43758721]
 [0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456]]
[14.25596638  5.71036058  5.871293  ]
[0.44386323 0.33367433 1.49407907]
[[-0.20515826  0.3130677 ]
 [-0.85409574 -2.55298982]]
[4.63404649 5.1610905  1.14458745]
[[12  7]
 [ 5  5]]

In [134]:
import numpy as np
my_list = ['a','b','c','d']
print(np.random.choice(my_list,2,replace=False,p=[0.1,0.7,0.1,0.1]))
print(np.random.choice(my_list,(3,3)))
print(np.random.permutation(my_list))
np.random.seed(0)
print(np.random.rand())
print(np.random.seed(0))
print(np.random.rand())

['b' 'a']
[['b' 'd' 'a']
 ['b' 'c' 'c']
 ['d' 'a' 'b']]
['a' 'c' 'd' 'b']
0.5488135039273248
None
0.5488135039273248

In [135]:
import numpy as np
import pandas as pd
df_csv = pd.read_csv('data/my_csv.csv')
print(df_csv)
df_txt = pd.read_table('data/my_table.txt')
print(df_txt)
df_excel = pd.read_excel('data/my_excel.xlsx')
print(df_excel)

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [136]:
pd.read_table('data/my_table.txt',header=None)

      0     1     2       3         4
0  col1  col2  col3    col4      col5
1     2     a   1.4   apple  2020/1/1
2     3     b   3.4  banana  2020/1/2
3     6     c   2.5  orange  2020/1/5

In [137]:
pd.read_csv('data/my_csv.csv',index_col=['col1','col2'])

           col3    col4      col5
col1 col2
2    a      1.4   apple  2020/1/1
3    b      3.4  banana  2020/1/2
6    c      2.5  orange  2020/1/5

In [138]:
pd.read_table('data/my_table.txt',usecols=['col1','col2'])

   col1 col2
0     2    a
1     3    b
2     6    c

In [139]:
pd.read_csv('data/my_csv.csv',parse_dates=['col5'])

   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05

In [140]:
pd.read_excel('data/my_excel.xlsx',nrows=2)

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2

In [141]:
pd.read_table('data/my_table_special_sep.txt')

              col1 |||| col2
0  TS |||| This is an apple.
1    GQ |||| My name is Bob.
2         WT |||| Well done!

In [142]:
pd.read_table('data/my_table_special_sep.txt',
              sep='\|\|\|\|',engine='python')

  col1                 col2
0   TS    This is an apple.
1   GQ      My name is Bob.
2   WT           Well done!

In [150]:
df_csv.to_csv('data/my_csv_saved.csv',index=False)
df_excel.to_excel('data/my_excel_saved.xlsx',index=False)
df_txt.to_csv('data/my_txt_saved.txt',sep='\t',index=False)
print(df_csv.to_markdown())
print(df_csv.to_latex())

|    |   col1 | col2   |   col3 | col4   | col5     |
|---:|-------:|:-------|-------:|:-------|:---------|
|  0 |      2 | a      |    1.4 | apple  | 2020/1/1 |
|  1 |      3 | b      |    3.4 | banana | 2020/1/2 |
|  2 |      6 | c      |    2.5 | orange | 2020/1/5 |
\begin{tabular}{lrlrll}
\toprule
 & col1 & col2 & col3 & col4 & col5 \\
\midrule
0 & 2 & a & 1.400000 & apple & 2020/1/1 \\
1 & 3 & b & 3.400000 & banana & 2020/1/2 \\
2 & 6 & c & 2.500000 & orange & 2020/1/5 \\
\bottomrule
\end{tabular}

In [159]:
s = pd.Series(data=[100,'a',{'dict1':5}],
              index=pd.Index(['id1',20,'third'],name='my_idx'),
              dtype='object',
              name='my_name')
print(s)
print(s.values)
print(s.index)
print(s.dtype)
print(s.name)
print(s.shape)
print(s['third'])

my_idx
id1               100
20                  a
third    {'dict1': 5}
Name: my_name, dtype: object
[100 'a' {'dict1': 5}]
Index(['id1', 20, 'third'], dtype='object', name='my_idx')
object
my_name
(3,)
{'dict1': 5}