In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('data/learn_pandas.csv',usecols = ['School','Grade','Name','Gender','Weight','Transfer'])
print(df['Name'].head())
print(df[['Gender','Name']].head())
df.Name.head()

0      Gaopeng Yang
1    Changqiang You
2           Mei Sun
3      Xiaojuan Sun
4       Gaojuan You
Name: Name, dtype: str
   Gender            Name
0  Female    Gaopeng Yang
1    Male  Changqiang You
2    Male         Mei Sun
3  Female    Xiaojuan Sun
4    Male     Gaojuan You

0      Gaopeng Yang
1    Changqiang You
2           Mei Sun
3      Xiaojuan Sun
4       Gaojuan You
Name: Name, dtype: str

In [2]:
s = pd.Series([1,2,3,4,5,6],index=['a','b','a','a','a','c'])
print(s['a'])
print(s['b'])
print(s[['c','b']])
s['c':'b':-2]

a    1
a    3
a    4
a    5
dtype: int64
2
c    6
b    2
dtype: int64

c    6
a    4
b    2
dtype: int64

In [3]:
s = pd.Series(['a','b','c','d','e','f'],index=[1,3,1,2,5,4])
print(s[1])
print(s[[2,3]])
s[1:-1:2]

1    a
1    c
dtype: str
2    d
3    b
dtype: str

3    b
2    d
dtype: str

In [4]:
df_demo = df.set_index('Name')
print(df_demo.head())
print(df_demo.loc['Qiang Sun'])
print(df_demo.loc['Quan Zhao'])
df_demo.loc['Qiang Sun','School']

               School      Grade  Gender  Weight Transfer
Name
Gaopeng Yang        A   Freshman  Female    46.0        N
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N
Gaojuan You         C  Sophomore    Male    74.0        N
          School      Grade  Gender  Weight Transfer
Name
Qiang Sun      D     Junior  Female    53.0        N
Qiang Sun      D  Sophomore  Female    40.0        N
Qiang Sun      A     Junior  Female     NaN        N
School           A
Grade       Junior
Gender      Female
Weight        53.0
Transfer         N
Name: Quan Zhao, dtype: object

Name
Qiang Sun    D
Qiang Sun    D
Qiang Sun    A
Name: School, dtype: str

In [5]:
print(df_demo.loc['Quan Zhao','School'])
print(df_demo.loc[['Qiang Sun','Quan Zhao'],['School','Gender']])
print(df_demo.loc['Gaojuan You':'Gaoqiang Qian','School':'Gender'])

A
          School  Gender
Name
Qiang Sun      D  Female
Qiang Sun      D  Female
Qiang Sun      A  Female
Quan Zhao      A  Female
              School      Grade  Gender
Name
Gaojuan You        C  Sophomore    Male
Xiaoli Qian        D   Freshman  Female
Qiang Chu          A   Freshman  Female
Gaoqiang Qian      D     Junior  Female

In [6]:
df_loc_slice_demo = df_demo.copy()
print(df_loc_slice_demo)
df_loc_slice_demo.index = range(df_demo.shape[0],0,-1)
print(df_loc_slice_demo.loc[5:3])
print(df_loc_slice_demo.loc[3:5])
df_demo.loc[df_demo.Weight>70].head()

               School      Grade  Gender  Weight Transfer
Name
Gaopeng Yang        A   Freshman  Female    46.0        N
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N
Gaojuan You         C  Sophomore    Male    74.0        N
...               ...        ...     ...     ...      ...
Xiaojuan Sun        C     Junior  Female    46.0        N
Li Zhao             D     Senior  Female    50.0        N
Chengqiang Chu      A     Senior  Female    45.0        N
Chengmei Shen       A     Senior    Male    71.0        N
Chunpeng Lv         D  Sophomore    Male    51.0        N

[200 rows x 5 columns]
  School   Grade  Gender  Weight Transfer
5      C  Junior  Female    46.0        N
4      D  Senior  Female    50.0        N
3      A  Senior  Female    45.0        N
Empty DataFrame
Columns: [School, Grade, Gender, Weight, Transfer]
Index: []

              School      Grade Gender  Weight Transfer
Name
Mei Sun            A     Senior   Male    89.0        N
Gaojuan You        C  Sophomore   Male    74.0        N
Xiaopeng Zhou      A   Freshman   Male    74.0        N
Xiaofeng Sun       D     Senior   Male    71.0        N
Qiang Zheng        A     Senior   Male    87.0        N

In [14]:
condition_1_1 = df_demo.School == 'A'
condition_1_2 = df_demo.Grade == 'Senior'
condition_1_3 = df_demo.Weight > 70
condition_1 = condition_1_1 & condition_1_2 & condition_1_3
condition_2_1 = df_demo.School == 'B'
condition_2_2 = df_demo.Grade == 'Senior'
condition_2_3 = df_demo.Weight > 80
condition_2 = condition_2_1 & (~condition_2_2) & condition_2_3
df_demo.loc[condition_1 | condition_2]

               School     Grade Gender  Weight Transfer
Name
Mei Sun             A    Senior   Male    89.0        N
Qiang Zheng         A    Senior   Male    87.0        N
Qiang Han           B  Freshman   Male    87.0        N
Changpeng Zhao      B  Freshman   Male    83.0        N
Gaoli Zhao          A    Senior   Male    83.0        N
Xiaofeng Zhang      A    Senior   Male    80.0        N
Chengmei Shen       A    Senior   Male    71.0        N

In [15]:
def condition(x):
    condition_1_1 = x.School == 'A'
    condition_1_2 = x.Grade == 'Senior'
    condition_1_3 = x.Weight > 70
    condition_1 = condition_1_1 & condition_1_2 & condition_1_3
    condition_2_1 = x.School == 'B'
    condition_2_2 = x.Grade == 'Senior'
    condition_2_3 = x.Weight > 80
    condition_2 = condition_2_1 & (~condition_2_2) & condition_2_3
    result = condition_1 | condition_2
    return result
df_demo.loc[condition]

               School     Grade Gender  Weight Transfer
Name
Mei Sun             A    Senior   Male    89.0        N
Qiang Zheng         A    Senior   Male    87.0        N
Qiang Han           B  Freshman   Male    87.0        N
Changpeng Zhao      B  Freshman   Male    83.0        N
Gaoli Zhao          A    Senior   Male    83.0        N
Xiaofeng Zhang      A    Senior   Male    80.0        N
Chengmei Shen       A    Senior   Male    71.0        N

In [17]:
print(df_demo.loc[lambda x:'Quan Zhao',lambda x:'Gender'])
df_demo.loc[lambda x:slice('Gaojuan You','Gaoqiang Qian')]

Female

              School      Grade  Gender  Weight Transfer
Name
Gaojuan You        C  Sophomore    Male    74.0        N
Xiaoli Qian        D   Freshman  Female    51.0        N
Qiang Chu          A   Freshman  Female    52.0        N
Gaoqiang Qian      D     Junior  Female    50.0        N

In [20]:
df_chain = pd.DataFrame([[0,0],[1,0],[-1,0]],columns=list('AB'))
print(df_chain)
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings('error')
    try:
        df_chain[df_chain.A !=0].B = 1
    except Warning as w:
        Warning_Msg = w
print(Warning_Msg)

   A  B
0  0  0
1  1  0
2 -1  0

NameError: name 'Warning_Msg' is not defined