In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('data/learn_pandas.csv',usecols=['School','Grade','Name','Gender','Weight','Transfer'])
df_multi = df.set_index(['School','Grade'])
res = df_multi.loc[(['A','B'],['Sophomore','Junior']),:]
print(res.head())
print(res.shape)

                            Name  Gender  Weight Transfer
School Grade
A      Sophomore    Yanfeng Qian  Female    48.0        N
       Sophomore        Gaoli Xu  Female    53.0        N
       Sophomore        Feng Han    Male    82.0        N
       Sophomore    Chunpeng Shi  Female    44.0        N
       Sophomore  Xiaoqiang Feng  Female    43.0        N
(35, 4)

In [5]:
res = df_multi.loc[[('A','Junior'),('B','Sophomore')]]
print(res.head())
print(res.shape)

                      Name  Gender  Weight Transfer
School Grade
A      Junior   Feng Zheng  Female    51.0        N
       Junior    Mei Zhang  Female    44.0        N
       Junior  Xiaoli Wang    Male    70.0        N
       Junior     Qiang Lv  Female    42.0        N
       Junior      Mei Sun  Female    50.0        N
(22, 4)

In [8]:
np.random.seed(0)
L1,L2 = ['A','B','C'],['a','b','c']
mul_index1 = pd.MultiIndex.from_product([L1,L2],names=('Upper','Lower'))
L3,L4 = ['D','E','F'],['d','e','f']
mul_index2 = pd.MultiIndex.from_product([L3,L4],names=('Big','Small'))
df_ex = pd.DataFrame(np.random.randint(-9,10,(9,9)),index=mul_index1,columns=mul_index2)
df_ex

Big          D        E        F
Small        d  e  f  d  e  f  d  e  f
Upper Lower
A     a      3  6 -9 -6 -6 -2  0  9 -5
      b     -3  3 -8 -3 -2  5  8 -4  4
      c     -1  0  7 -4  6  6 -9  9 -6
B     a      8  5 -2 -9 -8  0 -9  1 -6
      b      2  9 -7 -9 -9 -5 -4 -3 -1
      c      8  6 -5  0  1 -8 -8 -2  0
C     a     -6 -3  2  5  9 -9  5 -6  3
      b      1  2 -5 -3 -5  6 -6  3 -5
      c     -1  5  6 -6  6  4  7  8 -4

In [10]:
np.random.seed(0)
L1,L2,L3 = ['A','B'],['a','b'],['alpha','beta']
mul_index1 = pd.MultiIndex.from_product([L1,L2,L3],names=('Upper','Lower','Extra'))
L4,L5,L6 = ['C','D'],['c','d'],['cat','dog']
mul_index2 = pd.MultiIndex.from_product([L4,L5,L6],names=('Big','Small','Other'))
df_ex = pd.DataFrame(np.random.randint(-9,10,(8,8)),index=mul_index1,columns=mul_index2)
df_ex

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     alpha   3   6  -9  -6  -6  -2   0   9
            beta   -5  -3   3  -8  -3  -2   5   8
      b     alpha  -4   4  -1   0   7  -4   6   6
            beta   -9   9  -6   8   5  -2  -9  -8
B     a     alpha   0  -9   1  -6   2   9  -7  -9
            beta   -9  -5  -4  -3  -1   8   6  -5
      b     alpha   0   1  -8  -8  -2   0  -6  -3
            beta    2   5   9  -9   5  -6   3   1

In [13]:
print(df_ex.swaplevel(0,2,axis=1).head())
print(df_ex.reorder_levels([2,0,1],axis=0).head())

Other             cat dog cat dog cat dog cat dog
Small               c   c   d   d   c   c   d   d
Big                 C   C   C   C   D   D   D   D
Upper Lower Extra
A     a     alpha   3   6  -9  -6  -6  -2   0   9
            beta   -5  -3   3  -8  -3  -2   5   8
      b     alpha  -4   4  -1   0   7  -4   6   6
            beta   -9   9  -6   8   5  -2  -9  -8
B     a     alpha   0  -9   1  -6   2   9  -7  -9
Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Extra Upper Lower
alpha A     a       3   6  -9  -6  -6  -2   0   9
beta  A     a      -5  -3   3  -8  -3  -2   5   8
alpha A     b      -4   4  -1   0   7  -4   6   6
beta  A     b      -9   9  -6   8   5  -2  -9  -8
alpha B     a       0  -9   1  -6   2   9  -7  -9

In [ ]:
print(df_ex.droplevel(1,axis=1))
print(df_ex.droplevel([0,1],axis=0))

Big                 C               D
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     alpha   3   6  -9  -6  -6  -2   0   9
            beta   -5  -3   3  -8  -3  -2   5   8
      b     alpha  -4   4  -1   0   7  -4   6   6
            beta   -9   9  -6   8   5  -2  -9  -8
B     a     alpha   0  -9   1  -6   2   9  -7  -9
            beta   -9  -5  -4  -3  -1   8   6  -5
      b     alpha   0   1  -8  -8  -2   0  -6  -3
            beta    2   5   9  -9   5  -6   3   1

Big     C               D
Small   c       d       c       d
Other cat dog cat dog cat dog cat dog
Extra
alpha   3   6  -9  -6  -6  -2   0   9
beta   -5  -3   3  -8  -3  -2   5   8
alpha  -4   4  -1   0   7  -4   6   6
beta   -9   9  -6   8   5  -2  -9  -8
alpha   0  -9   1  -6   2   9  -7  -9
beta   -9  -5  -4  -3  -1   8   6  -5
alpha   0   1  -8  -8  -2   0  -6  -3
beta    2   5   9  -9   5  -6   3   1

In [20]:
print(df_ex.rename_axis(index={'Upper':'Changedrow_row'},columns={'Other':'Changed_Col'}).head())
print(df_ex.rename(columns={'cat':'not_cat'},level=2).head())
df_ex.rename(index=lambda x:str.upper(x),level=2).head()

Big                          C               D
Small                        c       d       c       d
Changed_Col                cat dog cat dog cat dog cat dog
Changedrow_row Lower Extra
A              a     alpha   3   6  -9  -6  -6  -2   0   9
                     beta   -5  -3   3  -8  -3  -2   5   8
               b     alpha  -4   4  -1   0   7  -4   6   6
                     beta   -9   9  -6   8   5  -2  -9  -8
B              a     alpha   0  -9   1  -6   2   9  -7  -9
Big                     C                       D
Small                   c           d           c           d
Other             not_cat dog not_cat dog not_cat dog not_cat dog
Upper Lower Extra
A     a     alpha       3   6      -9  -6      -6  -2       0   9
            beta       -5  -3       3  -8      -3  -2       5   8
      b     alpha      -4   4      -1   0       7  -4       6   6
            beta       -9   9      -6   8       5  -2      -9  -8
B     a     alpha       0  -9       1  -6       2   9      -7  -9

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     ALPHA   3   6  -9  -6  -6  -2   0   9
            BETA   -5  -3   3  -8  -3  -2   5   8
      b     ALPHA  -4   4  -1   0   7  -4   6   6
            BETA   -9   9  -6   8   5  -2  -9  -8
B     a     ALPHA   0  -9   1  -6   2   9  -7  -9

In [22]:
new_values = iter(list('abcdefgh'))
print(df_ex.rename(index=lambda x:next(new_values),level=2))
df_temp = df_ex.copy()
new_idx = df_temp.index.map(lambda x:(x[0],x[1],str.upper(x[2])))
df_temp.index = new_idx
df_temp.head()

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     a       3   6  -9  -6  -6  -2   0   9
            b      -5  -3   3  -8  -3  -2   5   8
      b     c      -4   4  -1   0   7  -4   6   6
            d      -9   9  -6   8   5  -2  -9  -8
B     a     e       0  -9   1  -6   2   9  -7  -9
            f      -9  -5  -4  -3  -1   8   6  -5
      b     g       0   1  -8  -8  -2   0  -6  -3
            h       2   5   9  -9   5  -6   3   1

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     ALPHA   3   6  -9  -6  -6  -2   0   9
            BETA   -5  -3   3  -8  -3  -2   5   8
      b     ALPHA  -4   4  -1   0   7  -4   6   6
            BETA   -9   9  -6   8   5  -2  -9  -8
B     a     ALPHA   0  -9   1  -6   2   9  -7  -9

In [30]:
import numpy as np
import pandas as pd
df = pd.read_csv('data/learn_pandas.csv')
print(df.groupby('Gender')['Height'].median())
print(df.groupby(['School','Gender'])['Height'].mean())
condition = df.Weight > df.Weight.mean()
print(df.groupby(condition)['Height'].mean())

Gender
Female    159.6
Male      173.4
Name: Height, dtype: float64
School  Gender
A       Female    159.122500
        Male      176.760000
B       Female    158.666667
        Male      172.030000
C       Female    158.776923
        Male      174.212500
D       Female    159.753333
        Male      171.638889
Name: Height, dtype: float64
Weight
False    159.034646
True     172.705357
Name: Height, dtype: float64

In [36]:
item = np.random.choice(list('abc'),df.shape[0])
print(df.groupby(item)['Height'].mean())
print(df.groupby([condition,item])['Height'].mean())
print(df[['School','Gender']].drop_duplicates())
df.groupby([df['School'],df['Gender']])['Height'].mean()

a    163.135821
b    162.095000
c    164.519643
Name: Height, dtype: float64
Weight
False   a    158.146512
        b    159.266667
        c    159.786111
True    a    172.075000
        b    173.408333
        c    173.040000
Name: Height, dtype: float64
   School  Gender
0       A  Female
1       B    Male
2       A    Male
3       C  Female
4       C    Male
5       D  Female
9       B  Female
16      D    Male

School  Gender
A       Female    159.122500
        Male      176.760000
B       Female    158.666667
        Male      172.030000
C       Female    158.776923
        Male      174.212500
D       Female    159.753333
        Male      171.638889
Name: Height, dtype: float64